# Interface schema
# https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/schema.html
# possible types are here
# - https://searchfox.org/mozilla-central/source/toolkit/components/extensions/Schemas.jsm#2418-2426
#
# - properties
# - functions
# - events
# - types
#
# - type property:
#   boolean, integer, number, string, array, object, or any.
#

---
- namespace: taarStudyMonitor
  description: Privileged code used to monitor the study

  functions:
  - name: onFirstRun
    type: 'function'
    async: true
    description: ''
    parameters: []
  - name: setAndPersistStatus
    type: 'function'
    async: true
    description: ''
    parameters: []
  - name: getStatus
    type: 'function'
    async: true
    description: ''
    parameters: []
  - name: incrementAndPersistClientStatusAboutAddonsActiveTabSeconds
    type: 'function'
    async: true
    description: ''
    parameters: []
  - name: reset
    type: 'function'
    async: true
    description: ''
    parameters: []
